baseURL = "https://MrEdEvans.github.io"
languageCode = "en-us"
title = "My New Hugo Site - V1.0.0"
theme = "ananke"
publishDir = "docs"
relativeURLs = true

[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
